<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE patient [
	<!ELEMENT patient (dob,dni,hemograms?)>
	<!ATTLIST patient name CDATA #REQUIRED surname CDATA #REQUIRED>
	<!ELEMENT dob (#PCDATA)>
	<!ELEMENT dni (#PCDATA)>
	<!ELEMENT hemograms (hemogram+)>
	<!ELEMENT hemogram (dob,comments?,doctor,analyzer)>
	<!ATTLIST hemogram id CDATA #REQUIRED>
	<!ELEMENT comments (#PCDATA)>
	<!ELEMENT doctor (work_user,hospital,specialty)>
	<!ATTLIST doctor name CDATA #REQUIRED surname CDATA #REQUIRED>
	<!ELEMENT work_user (#PCDATA)>
	<!ELEMENT hospital (#PCDATA)>
	<!ELEMENT specialty (#PCDATA)>
	<!ELEMENT analyzer (work_user,hospital)>
	<!ATTLIST analyzer name CDATA #REQUIRED surname CDATA #REQUIRED>
]>

<patient name="Mario" surname="Lopez">
    <dob>2020-05-04</dob>
    <dni>1234</dni>
    <hemograms>
        <hemogram id="8">
            <dob>2020-10-04</dob>
            <comments>holiwas</comments>
            <doctor name="Carlos" surname="Fernandez">
    			<work_user>lunes</work_user>
    			<hospital>rubber</hospital>
    			<specialty>cardiologist</specialty>
            </doctor>
            <analyzer name="Laura" surname="Sanchez">
    			<work_user>miercoles</work_user>
    			<hospital>rubber</hospital>
            </analyzer>
        </hemogram>
        
        <hemogram id="9">
            <dob>2020-11-04</dob>
            <comments>ey que pasa</comments>
            <doctor name="Roberto" surname="Jimenez">
    			<work_user>martes</work_user>
    			<hospital>clinico</hospital>
    			<specialty>cardiologist</specialty>
            </doctor>
            <analyzer name="Paula" surname="Fernandez">
    			<work_user>viernes</work_user>
    			<hospital>clinico</hospital>
            </analyzer>
        </hemogram>
        
    </hemograms>
</patient>